export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"


export const ORDER_DETAILS_REQUEST ="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS ="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL ="ORDER_DETAILS_FAIL"

export const ORDER_HISTORY_LIST_REQUEST = "ORDER_HISTORY_LIST_REQUEST"
export const ORDER_HISTORY_LIST_SCCUESS = "ORDER_HISTORY_LIST_SCCUESS"
export const ORDER_HISTORY_LIST_FAIL = "ORDER_HISTORY_LIST_FAIL"


export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"


export const ORDER_PREPARED_REQUEST = "ORDER_PREPARED_REQUEST"
export const ORDER_PREPARED_SUCCESS = "ORDER_PREPARED_SUCCESS"
export const ORDER_PREPARED_FAIL = "ORDER_PREPARED_FAIL"
export const ORDER_PREPARED_RESET = "ORDER_PREPARED_RESET"


export const ORDER_PICKED_UP_REQUEST = "ORDER_PICKED_UP_REQUEST"
export const ORDER_PICKED_UP_SUCCESS = "ORDER_PICKED_UP_SUCCESS"
export const ORDER_PICKED_UP_FAIL = "ORDER_PICKED_UP_FAIL"
export const ORDER_PICKED_UP_RESET = "ORDER_PICKED_UP_RESET"